### ISSUE TITLE
Provider not working

### ISSUE THREAD

**Issue by mikamakusa** [netascode/terraform-provider-iosxe#100]
Hi,

I'm testing your provider and the official one.
It seems your version is not working.

The resource on which I applied my configuration is the the following : 
```
resource "iosxe_access_list_standard" "example" {
  name = "SACL1"
  entries = [
    {
      sequence         = 10
      remark           = "Description"
      deny_prefix      = "10.0.0.0"
      deny_prefix_mask = "0.0.0.255"
    }
  ]
}
```

I keep getting the following error message : 
```
iosxe_access_list_standard.example: Creating...
╷
│ Error: Client Error
│ 
│   with iosxe_access_list_standard.example,
│   on provider.tf line 63, in resource "iosxe_access_list_standard" "example":
│   63: resource "iosxe_access_list_standard" "example" {
│ 
│ Failed to configure object (PATCH), got error: HTTP Request failed: StatusCode 401, RESTCONF errors {Error:[{ErrorType:protocol ErrorTag:access-denied ErrorAppTag: ErrorPath: ErrorMessage: ErrorInfo:}]} {PatchId:
│ GlobalStatus:{Ok:false Errors:{Error:[]}} EditStatus:{Edit:[]}}
```

When I try with the official one, no error message.

Terraform version : 
```
Terraform v1.4.2
on linux_amd64
+ provider terraform.local/local/iosxe v0.1.14

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by danischm** [comment]
Your are getting an "access-denied" response. Is the https server, restconf, a local user and authentication configured correctly? Can you share the config you used with the other provider?

**Comment by mikamakusa** [comment]
Like I said before : it's working with the official provider (CiscoDevNet/iosxe).
So a local user + authentication, the https server and restconf are correctly configured.

### CiscoDevNet provider
```
provider "iosxe" {
  device_password = "xxxxx"
  device_username = "xxxxxxxxx"
  host      = "https://192.168.1.1:443"
  insecure = true
}
```

### netascode provider
```
provider "iosxe" {
  password = "xxxxx"
  username = "xxxxxxxxx"
  url      = "https://192.168.1.1:443"
  insecure = true
}
```

**Comment by danischm** [comment]
I just tested the following config with the public devnet sandbox and it works:

```
provider "iosxe" {
  username = "admin"
  password = "C1sco12345"
  url      = "https://sandbox-iosxe-latest-1.cisco.com"
}

resource "iosxe_access_list_standard" "example" {
  name = "SACL1"
  entries = [
    {
      sequence         = 10
      remark           = "Description"
      deny_prefix      = "10.0.0.0"
      deny_prefix_mask = "0.0.0.255"
    }
  ]
}
```

Could you please verify if this works for you as well?

**Comment by mikamakusa** [comment]
On the devnet sandbox, it is working too...but not this one : 
```
resource "iosxe_vlan" "example" {
  vlan_id  = 123
  name     = "Vlan123"
  shutdown = false
}
```

On my hardware, restconf is set...but it seems I need netconf too in order to make the cisco providers working ?

**Comment by danischm** [comment]
The devnet sandbox is a Catalyst 8000v router. You cannot configure a VLAN on those devices. You would need to point it to Catalyst Switch for example.

**Comment by mikamakusa** [comment]
Thanks for your help.
Since it was the first time I get my hands on such hardware, I didn't know why I was able to set something with Terraform.
Now I know...it was because of restconf and netconf.
I've found some documentation and sent it to the hardware admin who performed the need tasks.

**Comment by mikamakusa** [comment]
Issue can be closed :)
