### ISSUE TITLE
interface config is not removed when removing resource 

### ISSUE THREAD

**Issue by mobig** [netascode/terraform-provider-iosxe#110]
Setting the params on an interface works as expected using `iosxe_interface_ethernet`. However, when removing the resource, i would expect any config set by terraform to be removed or nullified. This does not seem to be the case as the config persists even when the resource is removed

```
terraform {
  required_providers {
    iosxe = {
      source  = "netascode/iosxe"
      version = "0.1.15"
    }
  }
}

provider "iosxe" {
  username = "<user>"
  password = "<pw>"
  url      = "<url>"
}

resource "iosxe_interface_ethernet" "test" {
  type                           = "GigabitEthernet"
  name                           = "3"
  description                    = "My Interface Description"
  shutdown                       = false
  ipv4_address                   = null
  ipv4_address_mask              = "255.255.255.252"
  ip_dhcp_relay_source_interface = "Loopback100"
  ip_access_group_in             = "1"
  ip_access_group_in_enable      = true
  ip_access_group_out            = "1"
  ip_access_group_out_enable     = true
}
```

**Comment by danischm** [comment]
This is the expected behavior as for example the Cisco-IOS-XE-native:native/interface/GigabitEthernet container cannot be deleted.

**Comment by mobig** [comment]
i understand the interface can't be deleted, but i would expect the vales that are non-default to be nullified upon removal of the resource. in the terraform plan, it looks like the the provider is trying to do that, but the config never get's removed from the router. what this means is that once an ip address is set on an interface, it appears there is no way to remove it --`no ip address`, all you can do it change it.

**Comment by danischm** [comment]
Indeed, the plan output is the intend, but unfortunately the interface/api underneath currently does not support this in a scalable way.

**Comment by mobig** [comment]
understood. i guess this it just something we'll have to keep in mind. i'll close this issue

thanks for the response
