### ISSUE TITLE
Cisco-IOS-XE-acl:standard ErrorMessage:missing │ element: sequence in /ios:native/ios:ip/ios:access-list/ios-acl:standard[ios-acl:name='SACL1']/ios-acl:access-list-seq-rule

### ISSUE THREAD

**Issue by gsantos1979** [netascode/terraform-provider-iosxe#111]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.4.6

### Affected Resource(s)
- iosxe_access_list_standard
- 
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "iosxe_access_list_standard" "example" {
  name = "SACL1"
  entries = [
    {
      sequence         = 10
      remark           = "Description"
      deny_prefix      = "10.0.0.0"
      deny_prefix_mask = "0.0.0.255"
    }
  ]
}
```

### Expected Behavior
Create an ACL SACL1 with 1 entry on sequence 10

### Actual Behavior
```
iosxe_access_list_standard.example: Creating...
╷
│ Error: Client Error
│ 
│   with iosxe_access_list_standard.example,
│   on snmp.tf line 3, in resource "iosxe_access_list_standard" "example":
│    3: resource "iosxe_access_list_standard" "example" {
│ 
│ Failed to configure object (PATCH), got error: HTTP Request failed: StatusCode 400, RESTCONF errors {Error:[{ErrorType:application
│ ErrorTag:malformed-message ErrorAppTag: ErrorPath:/Cisco-IOS-XE-native:native/ip/access-list/Cisco-IOS-XE-acl:standard ErrorMessage:missing
│ element: sequence in /ios:native/ios:ip/ios:access-list/ios-acl:standard[ios-acl:name='SACL1']/ios-acl:access-list-seq-rule ErrorInfo:}]} {PatchId:
│ GlobalStatus:{Ok:false Errors:{Error:[]}} EditStatus:{Edit:[]}}
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by danischm** [comment]
Hmm, it does work for me (testing with the public devnet sandbox: sandbox-iosxe-latest-1.cisco.com). Which device is it and which SW version?

**Comment by gsantos1979** [comment]
It's a Cisco Catalyst 9500 Series Chassis, Model C9500-48Y4C, IOS version [Bengaluru], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.6.3, RELEASE SOFTWARE (fc4).

I'm only get your documentation example and paste in my terraform code...

**Comment by danischm** [comment]
That's odd. Can you try configuring the equivalent config via CLI and check if it's accepted?

**Comment by gsantos1979** [comment]
Yes, via CLI is working:

sw1(config)#ip access-list standard SACL1
sw1(config-std-nacl)#remark "Description"
sw1(config-std-nacl)#10 deny 10.0.0.0 0.0.0.255 
sw1(config-std-nacl)#end

sw1#show runn | sec SACL1
ip access-list standard SACL1
 10 remark "Description"
 10 deny   10.0.0.0 0.0.0.255
sw1parcore1-mgmt-new#show ip acess

sw1#show ip access-lists SACL1
Standard IP access list SACL1
    10 deny   10.0.0.0, wildcard bits 0.0.0.255

**Comment by danischm** [comment]
Do other resources work, e.g. setting a hostname via `iosxe_system`?

**Comment by gsantos1979** [comment]
I have applied all of this with success:

`resource "iosxe_system" "global" {
  for_each                      = toset([for router in local.routers : router.name])

  device                      = each.key
  hostname                = each.key
  mtu                           = 9124
  ip_routing                    = true
  ip_domain_lookup      = true
  ip_domain_name         = "domain.name"
}
`

**Comment by danischm** [comment]
Could you enable debug logging (`export TF_LOG=Trace`), remove any potential sensitive information and share the log?

**Comment by gsantos1979** [comment]
Can you share an e-mail to send the file ? I'm receiving the following error:
You can't comment at this time — your comment is too long (maximum is 65536 characters).

**Comment by gsantos1979** [comment]
[debug_netascode_acl.txt](https://github.com/netascode/terraform-provider-iosxe/files/11824451/debug_netascode_acl.txt)

**Comment by danischm** [comment]
Thanks. I believe I have identified the issue. Apparently a certain leaf of the YANG model has been deprecated and support for it has been dropped in newer releases. I need to run some internal tests first.

**Comment by danischm** [comment]
I have just release 0.1.17 which hopefully fixes the issue.

**Comment by gsantos1979** [comment]
It's working now. Thanks.

Just one last question: I'm trying to use your generic resource (resource "iosxe_restconf") to make settings not covered by the module (eg NTP).
Where can I find documentation regarding which parameters need to be passed using this resource in lists and attributes? I'm having a hard time finding documentation of what is expected for each item, which attributes are required, etc.

I greatly appreciate your help.

**Comment by danischm** [comment]
You would have to understand the underlying YANG models being used by IOS-XE. One way to visualize and browse them would be using YANG suite (https://developer.cisco.com/yangsuite/). Another approach would be to configure a specific feature using the CLI first and then use `show run | format restconf-json` to show the YANG-modelled configuration.

**Comment by gsantos1979** [comment]
Thank you for your assistance.
