### ISSUE TITLE
Error: The terraform-provider-iosxe_v0.1.4 plugin crashed!

### ISSUE THREAD

**Issue by muhammad-rafi** [netascode/terraform-provider-iosxe#12]
### Terraform Version
```
$ terraform -v
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/netascode/iosxe v0.1.4

Your version of Terraform is out of date! The latest version
is 1.1.9. You can update by downloading from https://www.terraform.io/downloads.html
```

### Go Version
```
$ go version
go version go1.18.2 darwin/amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- iosxe_static_route

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
https://github.com/muhammad-rafi/terraform-iosxe/blob/main/ntc_iosxe/static_routing.tf

```hcl
terraform {
  required_providers {
    iosxe = {
      source  = "netascode/iosxe"
      version = "0.1.4"
    }
  }
}

# Network To Code iosxe Provider Configuration
provider "iosxe" {
  alias    = "cisco_sandbox"
  username = "developer"
  password = "C1sco12345"
  url      = "https://sandbox-iosxe-recomm-1.cisco.com"
}

resource "iosxe_static_route" "static_route" {
  provider   = iosxe.cisco_sandbox
  device = "sandbox-iosxe-recomm-1.cisco.com"
  prefix = "10.0.0.10"
  mask   = "255.255.255.0"
  next_hops = [
    {
      next_hop  = "10.0.0.1"
      metric    = 10
      global    = false
      name      = "terraform_route"
      permanent = true
      tag       = 100
    }
  ]
}
```

### Debug Output
https://gist.github.com/muhammad-rafi/8c2b8e6ef2fd74d596ed54694fc3991b

### Expected Behavior
It should configure the static route on the iosxe device 

### Actual Behavior
Error: The terraform-provider-iosxe_v0.1.4 plugin crashed!

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply -auto-approve`

**Comment by danischm** [comment]
Hi @muhammad-rafi ! The `device` attribute under the resource refers to a device specified in the provider configuration. Please refer to this guide: https://registry.terraform.io/providers/netascode/iosxe/latest/docs/guides/manage_multiple_devices . If you just want to configure a single device there is no need to specify a device, you can simply omit the resource attribute. Please note that the provided prefix/mask is incorrect as `10.0.0.10/24` is not a network address. You can try the following config instead:

```terraform
terraform {
  required_providers {
    iosxe = {
      source  = "netascode/iosxe"
      version = "0.1.4"
    }
  }
}

# Network To Code iosxe Provider Configuration
provider "iosxe" {
  alias    = "cisco_sandbox"
  username = "developer"
  password = "C1sco12345"
  url      = "https://sandbox-iosxe-recomm-1.cisco.com"
}

resource "iosxe_static_route" "static_route" {
  provider   = iosxe.cisco_sandbox
  prefix = "10.1.1.0"
  mask   = "255.255.255.0"
  next_hops = [
    {
      next_hop  = "10.0.0.1"
      metric    = 10
      global    = false
      name      = "terraform_route"
      permanent = true
      tag       = 100
    }
  ]
}
```

**Comment by muhammad-rafi** [comment]
@danischm thanks for the guidance and point out the error in the config, I am only starting out with the terraform and started with this repo and one thing I can surely it really looks good. thank you for the hard work. 

One thing, I wanted to know, to delete the resource, do we just have to destroy ? or can we define in the resource block ? 

You may also close the issue, thank you for the help.

**Comment by danischm** [comment]
Yes, if you remove the resource from your config and do a `terraform apply` it should remove the route. Same if you do a `terraform destroy`.
