### ISSUE TITLE
IOSXE-ALC

### ISSUE THREAD

**Issue by diyvol777** [netascode/terraform-provider-iosxe#44]
Hi,
I'm appreciate your work! I'm going to use the terraform for my infrastructure where I have to support more 500 switches which will operate as fabric. I'd like ask you add several resources. The first resources is a ACL (We need use a lot of ACL for restrict access between vlan) and the second resources is  base configuration (domain name, ssh configuration, enable/disable service,configuration logging) The most important resources is ACL.

**Comment by danischm** [comment]
Hi @diyvol777! Thanks for your feedback. Would you mind adding sample cli configuration snippets to better understand which specific commands/options you require?

**Comment by diyvol777** [comment]
This is part of my configuration from switch which I have to distribute to all my switches.
conf t
no service pad
service tcp-keepalives-in
service tcp-keepalives-out
service timestamps debug datetime msec localtime show-timezone
service timestamps log datetime msec localtime show-timezone

logging buffered 64000
logging console critical
no ip source-route
no ip domain lookup
ip domain name test.com
login block-for 900 attempts 5 within 900
login delay 10
login on-failure log
login on-success log
logging source-interface Vlan254
logging host 10.10.254.95
logging host 10.10.254.111
logging host 10.10.10.196
logging host 10.10.10.196 transport udp port 10100

snmp-server group TEST_GROUP v3 priv read ERG_VIEW_READ access 99
snmp-server view TEST_VIEW_READ iso included
snmp-server view TEST_VIEW_READ interfaces included
snmp-server view TEST_VIEW_READ ifDescr included
snmp-server view TEST_VIEW_READ ifType included
snmp-server view TEST_VIEW_READ ifAdminStatus included
snmp-server view TEST_VIEW_READ ifOperStatus included
snmp-server enable traps snmp authentication linkdown linkup coldstart

**Comment by danischm** [comment]
https://github.com/netascode/terraform-provider-iosxe/commit/ad4133b0ba8072bb72f1e4b65fbe89ba80f33e28

**Comment by danischm** [comment]
https://github.com/netascode/terraform-provider-iosxe/commit/bd2b8dc6812f7a427f77611ff2f642b29de9de7f
https://github.com/netascode/terraform-provider-iosxe/commit/a7ac3ab0066d3a0d61d39f3633413ba08ea0363e
https://github.com/netascode/terraform-provider-iosxe/commit/3be1fb4d73111a7d71e3f5cb6cbb59de57ad4ea9
https://github.com/netascode/terraform-provider-iosxe/commit/6b93a26e0fe47b7ee7dfaeabd87943111b1ce7e1
https://github.com/netascode/terraform-provider-iosxe/commit/62d22bdf34900d060c50e40c408514d17b746817

**Comment by danischm** [comment]
https://github.com/netascode/terraform-provider-iosxe/commit/73a70cf14073439a91fb45278f2fe114e66e68b7

**Comment by diyvol777** [comment]
Hi! Thanks for your work!!! I appreciate it! Could you add ACL configuration too? I haven't added part of ACL configuration. Or I can make new request, how is more convenient ?

example:
(config)#ip access-list extended acl-USER-STANDARD-in
(config-ext-nacl)#permit tcp 10.4.64.0 0.0.0.255 10.4.231.0 0.0.0.255

(config)#ip access-list standart acl-USER-STANDARD-01-in
(config-std-nacl)#permit 10.0.0.0 0.0.0.255
(config-std-nacl)#permit host 10.4.4.1

**Comment by danischm** [comment]
https://github.com/netascode/terraform-provider-iosxe/commit/341c6fe51b87b547ac191c7c1dc3d00e68a540ac

**Comment by danischm** [comment]
I have published version 0.1.10 which should have resources for all the system-wide configurations from your previous example. I will look at ACLs next.

**Comment by diyvol777** [comment]
Thank you! This is good news for me!!!

**Comment by diyvol777** [comment]
terraform apply -auto-approve
module.modules.iosxe_rest.bgp_example_patch: Refreshing state... [id=2645902358]
module.modules.iosxe_rest.bgp_example_delete: Refreshing state... [id=141054560]
module.modules.iosxe_rest.bgp_example_get: Refreshing state... [id=1554969011]
module.modules.iosxe_rest.acl_example_get_id: Refreshing state... [id=2318200609]
module.modules.iosxe_rest.bgp_example_post: Refreshing state... [id=151008753]
module.modules.iosxe_rest.acl_example_get: Refreshing state... [id=2312439396]
module.modules.iosxe_rest.acl_example_patch: Refreshing state... [id=3687808702]
module.modules.iosxe_rest.bgp_example_get_id: Refreshing state... [id=1948995312]
module.modules.iosxe_rest.bgp_example_put: Refreshing state... [id=3517091002]
iosxe_interface_loopback.loopback100: Refreshing state... [id=Cisco-IOS-XE-native:native/interface/Loopback=100]
iosxe_username.newusername: Refreshing state... [id=Cisco-IOS-XE-native:native/username=test]
iosxe_banner.example: Refreshing state... [id=Cisco-IOS-XE-native:native/banner]
iosxe_service.example: Refreshing state... [id=Cisco-IOS-XE-native:native/service]
iosxe_vrf.VRF-10: Refreshing state... [id=Cisco-IOS-XE-native:native/vrf/definition=VRF10]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # iosxe_service.example will be updated in-place
  ~ resource "iosxe_service" "example" {
      + dhcp                                    = (known after apply)
        id                                      = "Cisco-IOS-XE-native:native/service"
      + timestamps_debug                        = true
      + timestamps_debug_datetime               = true
      + timestamps_debug_datetime_localtime     = true
      + timestamps_debug_datetime_msec          = true
      + timestamps_debug_datetime_show_timezone = true
      + timestamps_debug_datetime_year          = true
      + timestamps_debug_uptime                 = true
      + timestamps_log                          = (known after apply)
      + timestamps_log_datetime                 = (known after apply)
      + timestamps_log_datetime_localtime       = (known after apply)
      + timestamps_log_datetime_msec            = (known after apply)
      + timestamps_log_datetime_show_timezone   = (known after apply)
      + timestamps_log_datetime_year            = (known after apply)
      + timestamps_log_uptime                   = (known after apply)
        # (6 unchanged attributes hidden)
    }

  # iosxe_username.newusername will be updated in-place
  ~ resource "iosxe_username" "newusername" {
      + description         = (known after apply)
        id                  = "Cisco-IOS-XE-native:native/username=test"
        name                = "test"
      + password            = (known after apply)
      + password_encryption = (known after apply)
      ~ secret              = "$1$Tgauakjshdsldkjalskdj0" -> "test"
      ~ secret_encryption   = "5" -> "0"
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
iosxe_username.newusername: Modifying... [id=Cisco-IOS-XE-native:native/username=test
iosxe_service.example: Modifying... [id=Cisco-IOS-XE-native:native/service]
iosxe_username.newusername: Modifications complete after 0s [id=Cisco-IOS-XE-native:native/username=test]
╷
│ Error: Client Error
│ 
│   with iosxe_service.example,
│   on servises.tf line 2, in resource "iosxe_service" "example":
│    2: resource "iosxe_service" "example" {
│ 
│ Failed to configure object (PATCH), got error: HTTP Request failed: StatusCode 400, RESTCONF errors {Error:[{ErrorType:application ErrorTag:malformed-message ErrorAppTag: ErrorPath:/Cisco-IOS-XE-native:native/service
│ ErrorMessage:unknown element: debug-config in /ios:native/ios:service/ios:timestamps/ios:debug-config ErrorInfo:}]} {PatchId: GlobalStatus:{Ok:false Errors:{Error:[]}} EditStatus:{Edit:[]}}

**Comment by diyvol777** [comment]
terraform apply -auto-approve
module.modules.iosxe_rest.acl_example_get_id: Refreshing state... [id=2318200609]
module.modules.iosxe_rest.bgp_example_put: Refreshing state... [id=3517091002]
module.modules.iosxe_rest.acl_example_patch: Refreshing state... [id=3687808702]
module.modules.iosxe_rest.bgp_example_patch: Refreshing state... [id=2645902358]
module.modules.iosxe_rest.bgp_example_get: Refreshing state... [id=1554969011]
module.modules.iosxe_rest.acl_example_get: Refreshing state... [id=2312439396]
module.modules.iosxe_rest.bgp_example_get_id: Refreshing state... [id=1948995312]
module.modules.iosxe_rest.bgp_example_delete: Refreshing state... [id=141054560]
module.modules.iosxe_rest.bgp_example_post: Refreshing state... [id=151008753]
iosxe_banner.example: Refreshing state... [id=Cisco-IOS-XE-native:native/banner]
iosxe_username.newusername: Refreshing state... [id=Cisco-IOS-XE-native:native/username=test_user]
iosxe_interface_loopback.loopback100: Refreshing state... [id=Cisco-IOS-XE-native:native/interface/Loopback=100]
iosxe_service.example: Refreshing state... [id=Cisco-IOS-XE-native:native/service]
iosxe_vrf.VRF-10: Refreshing state... [id=Cisco-IOS-XE-native:native/vrf/definition=VRF10]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # iosxe_service.example will be updated in-place
  ~ resource "iosxe_service" "example" {
      + dhcp                                    = (known after apply)
        id                                      = "Cisco-IOS-XE-native:native/service"
      + timestamps_debug                        = (known after apply)
      + timestamps_debug_datetime               = (known after apply)
      + timestamps_debug_datetime_localtime     = (known after apply)
      + timestamps_debug_datetime_msec          = (known after apply)
      + timestamps_debug_datetime_show_timezone = (known after apply)
      + timestamps_debug_datetime_year          = (known after apply)
      + timestamps_debug_uptime                 = (known after apply)
      + timestamps_log                          = true
      + timestamps_log_datetime                 = true
      + timestamps_log_datetime_localtime       = true
      + timestamps_log_datetime_msec            = true
      + timestamps_log_datetime_show_timezone   = true
      + timestamps_log_datetime_year            = true
      + timestamps_log_uptime                   = true
        # (6 unchanged attributes hidden)
    }

  # iosxe_username.newusername will be updated in-place
  ~ resource "iosxe_username" "newusername" {
      + description         = (known after apply)
        id                  = "Cisco-IOS-XE-native:native/username=test_user"
        name                = "test_user"
      + password            = (known after apply)
      + password_encryption = (known after apply)
      ~ secret              = "$1$sfuE$eycSnRalENEt9jpxDmU1c/" -> "test"
      ~ secret_encryption   = "5" -> "0"
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
iosxe_username.newusername: Modifying... [id=Cisco-IOS-XE-native:native/username=test_user]
iosxe_service.example: Modifying... [id=Cisco-IOS-XE-native:native/service]
iosxe_username.newusername: Modifications complete after 0s [id=Cisco-IOS-XE-native:native/username=test_user]
╷
│ Error: Client Error
│ 
│   with iosxe_service.example,
│   on servises.tf line 2, in resource "iosxe_service" "example":
│    2: resource "iosxe_service" "example" {
│ 
│ Failed to configure object (PATCH), got error: HTTP Request failed: StatusCode 400, RESTCONF errors {Error:[{ErrorType:application ErrorTag:malformed-message ErrorAppTag: ErrorPath:/Cisco-IOS-XE-native:native/service
│ ErrorMessage:unknown element: log-config in /ios:native/ios:service/ios:timestamps/ios:log-config ErrorInfo:}]} {PatchId: GlobalStatus:{Ok:false Errors:{Error:[]}} EditStatus:{Edit:[]}}

**Comment by danischm** [comment]
If the resources do not work as expected please post a non-working sample configuration. Thanks!

**Comment by danischm** [comment]
https://github.com/netascode/terraform-provider-iosxe/commit/5f67cb1406068d33c207f22e27d560cb5b7000b2

**Comment by danischm** [comment]
https://github.com/netascode/terraform-provider-iosxe/commit/d1d8f922a5c025f0ccdaa4fd0c78bcbe309cb0c2

**Comment by danischm** [comment]
I have added support for ACLs in the 0.1.11 release.

**Comment by diyvol777** [comment]
Thank you!!!
I missed part of a configuration snmp, does it possible to add it?

snmp-server userTEST_USER TEST_GROUP v3 auth sha test priv aes 128 test access 99

**Comment by danischm** [comment]
Added support for snmp users: https://github.com/netascode/terraform-provider-iosxe/commit/2b7f93fa8228bbf991462dfa892d3b904b695efa

**Comment by danischm** [comment]
I am publishing version 0.1.12 which has support for SNMP users.

**Comment by diyvol777** [comment]
Thank you!!! I'm appreciate your work!

**Comment by diyvol777** [comment]
Could you check the snmp-user? 

resource "iosxe_snmp_server_user" "example" {
  username                         = "USER"
  grpname                          = "GROUP"
  v3_auth_algorithm                = "sha"
  v3_auth_password                 = "Cisco123"
  v3_auth_priv_aes_algorithm       = "128"
  v3_auth_priv_aes_password        = "Cisco123"
#  v3_auth_priv_aes_access_ipv6_acl = "V6ACL1"
  v3_auth_priv_aes_access_acl_name = "ACL123"
}


│ Error: Client Error
│ 
│   with iosxe_snmp_server_user.example,
│   on snmp_server_user.tf line 1, in resource "iosxe_snmp_server_user" "example":
│    1: resource "iosxe_snmp_server_user" "example" {
│ 
│ Failed to configure object (PATCH), got error: HTTP Request failed: StatusCode 400, RESTCONF errors {Error:[{ErrorType:application
│ ErrorTag:malformed-message ErrorAppTag: ErrorPath:/Cisco-IOS-XE-native:native/snmp-server/Cisco-IOS-XE-snmp:user/names ErrorMessage:unknown
│ element: auth-config in
│ /ios:native/ios:snmp-server/ios-snmp:user/ios-snmp:names[ios-snmp:username='USER'][ios-snmp:grpname='GROUP']/ios-snmp:v3/ios-snmp:auth-config
│ ErrorInfo:}]} {PatchId: GlobalStatus:{Ok:false Errors:{Error:[]}} EditStatus:{Edit:[]}}

**Comment by danischm** [comment]
It works for me on IOS-XE 17.9 . What version are you running? Can you maybe try without the ACLs?

**Comment by diyvol777** [comment]
You are right! I had the ios 16.2 after upgrade to 17.3.5 my error was resolved. Thank you!
