### ISSUE TITLE
Request for Documentation Example (iosxe_restconf  resource)

### ISSUE THREAD

**Issue by eckdd** [netascode/terraform-provider-iosxe#82]
Hi,

I would like to see additional examples that employ objects with the list attribute for the iosxe_restconf  resource. 

Thanks

**Comment by danischm** [comment]
I will add this example to the documentation:

```
resource "iosxe_restconf" "example" {
  path = "Cisco-IOS-XE-native:native/ip"
  attributes = {
    source-route = "true"
  }
  lists = [{
    name = "vrf"
    key  = "name"
    items = [{
      attributes = {
        name = "VRF1"
      }
    }]
  }]
}
```

**Comment by danischm** [comment]
https://github.com/netascode/terraform-provider-iosxe/commit/ebe371899c4328d97b176a58302099904b9d454a

**Comment by danischm** [comment]
Does that answer your question?
